//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX.Core.Keys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FX.Core.Keys.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1466CF29-01F7-4B16-BD2C-7A8591713328}.
        /// </summary>
        public static string BusinessTypes {
            get {
                return ResourceManager.GetString("BusinessTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {DFC7ED31-CBB7-49F0-9E2D-F7BB358DE827}.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {28A504B9-A822-4611-88AD-B8F381D6EB47}.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3F503265-E907-44BD-9F91-2366828DD892}.
        /// </summary>
        public static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {106E7FFF-C985-4394-87C5-6D18287E04CD}.
        /// </summary>
        public static string OpcosDictionaryListField {
            get {
                return ResourceManager.GetString("OpcosDictionaryListField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EF70B3DC-BC80-4833-BA03-37E0AECA52C1}.
        /// </summary>
        public static string ProductsFolder {
            get {
                return ResourceManager.GetString("ProductsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2EDD7515-EB53-49DD-82FD-3E1FBD7F76F4}.
        /// </summary>
        public static string ProxyDictionaryOpcos {
            get {
                return ResourceManager.GetString("ProxyDictionaryOpcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1DF28E63-E518-4ABB-8FE5-9A07EA767811}.
        /// </summary>
        public static string ProxyOpcosLangList {
            get {
                return ResourceManager.GetString("ProxyOpcosLangList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {C5085500-519B-492F-82C6-7B0E16854FFF}.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {8B275731-F9CD-4CFB-B35D-4B23C4F8274B}.
        /// </summary>
        public static string SolutionsAndServices {
            get {
                return ResourceManager.GetString("SolutionsAndServices", resourceCulture);
            }
        }
    }
}
