//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX.Core.Keys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RenderingItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RenderingItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FX.Core.Keys.RenderingItems", typeof(RenderingItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {74D184DD-02CE-40D8-BA8A-6726691C294E}.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {27AE9AF0-79D5-4821-99D7-0DAC2CE3608E}.
        /// </summary>
        public static string Breadcrumb {
            get {
                return ResourceManager.GetString("Breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1EF24291-CDDF-4DD0-A86C-81C27B3FDF79}.
        /// </summary>
        public static string CtaPanel {
            get {
                return ResourceManager.GetString("CtaPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2185266A-CBF2-43B7-9373-C51E28BCE5DC}.
        /// </summary>
        public static string GeneralLinks {
            get {
                return ResourceManager.GetString("GeneralLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {D7D2211A-8FD8-49A2-B3E7-C8D53A9919F4}.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EE6DEB93-90A1-451F-A402-4D4F676C76F3}.
        /// </summary>
        public static string HeroBanner {
            get {
                return ResourceManager.GetString("HeroBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {D8F63639-052A-4BB6-A838-2E97C886C5B2}.
        /// </summary>
        public static string MainNavigation {
            get {
                return ResourceManager.GetString("MainNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {A6EF2F17-D850-4340-9DD4-625DDC2BD971}.
        /// </summary>
        public static string MicrositeBreadcrumb {
            get {
                return ResourceManager.GetString("MicrositeBreadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {14A849AD-540C-4943-8A63-C2E5CB406AAF}.
        /// </summary>
        public static string MicrositeContactForm {
            get {
                return ResourceManager.GetString("MicrositeContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AF6F79BA-0AF1-4551-8B17-79BA3FD6AA5A}.
        /// </summary>
        public static string MicrositeFooter {
            get {
                return ResourceManager.GetString("MicrositeFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3A206E3C-D1DC-496F-B9B3-D4B12EEAF4C2}.
        /// </summary>
        public static string MicrositeHead {
            get {
                return ResourceManager.GetString("MicrositeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3D0CED93-C984-481F-B9B8-650A021B1AB2}.
        /// </summary>
        public static string MicrositeHeader {
            get {
                return ResourceManager.GetString("MicrositeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6A1D5FAA-5766-487B-BD8C-8DF4FA34F593}.
        /// </summary>
        public static string MicrositeNavigation {
            get {
                return ResourceManager.GetString("MicrositeNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {306CE020-EAA3-44E8-AE93-45A958EB12A4}.
        /// </summary>
        public static string MicrositeSubNavigation {
            get {
                return ResourceManager.GetString("MicrositeSubNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {C5EE3FC7-7E20-4A34-916F-157A9E89B818}.
        /// </summary>
        public static string ProductHeroBanner {
            get {
                return ResourceManager.GetString("ProductHeroBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4C7CA6FC-1105-4EC7-A04C-E4741E9B9A4D}.
        /// </summary>
        public static string RecommendedProducts {
            get {
                return ResourceManager.GetString("RecommendedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {462BEF45-3089-4136-9AE7-6613DB0A8EA7}.
        /// </summary>
        public static string SiblingNavigation {
            get {
                return ResourceManager.GetString("SiblingNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {E1B93F86-9A0D-4B9B-B22C-392542F2FE26}.
        /// </summary>
        public static string SideMenu {
            get {
                return ResourceManager.GetString("SideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EC47B587-69F9-40DF-8818-8163A014EAFC}.
        /// </summary>
        public static string TopBanner {
            get {
                return ResourceManager.GetString("TopBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {F2CCA16D-7524-4E99-8EE0-78FF6394A3B3}.
        /// </summary>
        public static string WFFMMVCForm {
            get {
                return ResourceManager.GetString("WFFMMVCForm", resourceCulture);
            }
        }
    }
}
